training_data = [
    (["wizard", "magic", "spell", "enchantress", "sorcerer"], "fantasy"),
    (["dragon", "knight", "castle", "sword", "princess"], "fantasy"),
    (["elf", "dwarf", "orc", "troll", "hobbit"], "fantasy"),
    (["fairy", "pixie", "nymph", "sprite", "leprechaun"], "fantasy"),
    (["quest", "adventure", "prophecy", "legend", "myth"], "fantasy"),
    (["sorcery", "enchantment", "charm", "curse", "magical"], "fantasy"),
    (["fabled", "mystical", "otherworldly", "fantastical", "supernatural"], "fantasy"),
    (["portal", "dimension", "alternate", "realm", "parallel"], "fantasy"),
    (["knightly", "chivalrous", "honor", "courage", "valor"], "fantasy"),
    (["fate", "destiny", "chosen one", "prophecy", "oracle"], "fantasy"),
    (["mythical", "legendary", "ancient", "epic", "mythos"], "fantasy"),
    (["dungeon", "treasure", "trap", "monster", "loot"], "fantasy"),
    (["dragonslayer", "hero", "villain", "magic wand", "flying broom"], "fantasy"),
    (["dragon", "unicorn", "phoenix", "griffin", "pegasus"], "fantasy"),
    (["medieval", "renaissance", "feudal", "kingdom", "royalty"], "fantasy"),
    (["fairytale", "folklore", "nursery rhyme", "tall tale", "legend"], "fantasy"),
    (["magic carpet", "genie", "arabian nights", "sultan", "aladdin"], "fantasy"),
    (["time travel", "time machine", "temporal paradox", "time loop", "alternate history"], "fantasy"),
    (["enchanted forest", "cottage in the woods", "magical garden", "wishing well", "fairy ring"], "fantasy"),
    (["mythical creatures", "magical beasts", "cryptozoology", "folk monsters", "monstrous races"], "fantasy"),
    (["robot", "cyborg", "android", "machine", "artificial intelligence"], "science fiction"),
    (["spaceship", "galaxy", "planet", "alien", "extraterrestrial"], "science fiction"),
    (["time machine", "time travel", "temporal paradox", "chrononaut"], "science fiction"),
    (["cybernetics", "implants", "augmentation", "prosthetics"], "science fiction"),
    (["teleportation", "teleporter", "portal", "wormhole"], "science fiction"),
    (["nanotechnology", "nanobots", "nanomachines", "nanites"], "science fiction"),
    (["virtual reality", "simulation", "matrix", "cyberspace"], "science fiction"),
    (["artificial life", "synthetic biology", "cloning", "genetic engineering"], "science fiction"),
    (["cyberpunk", "dystopia", "post-apocalyptic", "surveillance"], "science fiction"),
    (["quantum mechanics", "quantum entanglement", "superposition", "multiverse"], "science fiction"),
    (["cyberspace", "cybersecurity", "hacking", "data breach"], "science fiction"),
    (["neural interface", "brain-machine interface", "mind uploading"], "science fiction"),
    (["cyberwarfare", "cyberweapons", "cyberattacks", "hacktivism"], "science fiction"),
    (["android uprising", "robot rebellion", "artificial intelligence apocalypse"], "science fiction"),
    (["terraforming", "colony", "interstellar travel", "generation ship"], "science fiction"),
    (["cybernetic organism", "cyborg", "bionic", "augmented human"], "science fiction"),
    (["robotics", "automation", "industry 4.0", "smart factories"], "science fiction"),
    (["science fantasy", "space opera", "planetary romance", "galactic empire"], "science fiction"),
    (["singularity", "technological singularity", "intelligence explosion", "AI takeover"], "science fiction"),
    (["cyber culture", "transhumanism", "cyborg anthropology", "cyberfeminism"], "science fiction"),
    (["detective", "murder", "mystery", "crime", "suspense"], "crime fiction"),
    (["investigation", "clue", "evidence", "police", "forensic"], "crime fiction"),
    (["thriller", "serial killer", "psychopath", "killer", "manhunt"], "crime fiction"),
    (["heist", "robbery", "burglary", "criminal", "con artist"], "crime fiction"),
    (["whodunit", "sleuth", "private investigator", "noir", "double cross"], "crime fiction"),
    (["organized crime", "mafia", "gang", "drug lord", "smuggling"], "crime fiction"),
    (["corruption", "cover-up", "crooked", "bribery", "scandal"], "crime fiction"),
    (["legal thriller", "courtroom drama", "lawyer", "judge", "jury"], "crime fiction"),
    (["cybercrime", "hacking", "identity theft", "cyber security", "data breach"], "crime fiction"),
    (["political thriller", "espionage", "spy", "assassination", "sabotage"], "crime fiction"),
    (["historical crime", "mystery", "detective", "investigation", "murder"], "crime fiction"),
    (["true crime", "non-fiction", "serial killer", "crime history", "investigation"], "crime fiction"),
    (["cozy mystery", "amateur detective", "small town", "whimsical", "quaint"], "crime fiction"),
    (["forensic thriller", "science", "medicine", "pathology", "autopsy"], "crime fiction"),
    (["murder mystery", "whodunit", "detective", "sleuth", "clue"], "crime fiction"),
    (["cold case", "unsolved", "long-forgotten", "mystery", "investigation"], "crime fiction"),
    (["neo-noir", "modern", "dark", "gritty", "edgy"], "crime fiction"),
    (["psychological thriller", "mind games", "manipulation", "suspense", "twist"], "crime fiction"),
    (["procedural", "police procedural", "investigation", "methodical", "detail-oriented"], "crime fiction"),
    (["action thriller", "fast-paced", "explosions", "chases", "adrenaline"], "crime fiction"),
    (["love", "romance", "passion", "affection", "devotion"], "romance"),
    (["kiss", "hug", "embrace", "cuddle", "caress"], "romance"),
    (["heart", "heartbeat", "flutter", "pounding", "thump"], "romance"),
    (["desire", "longing", "yearning", "craving", "hunger"], "romance"),
    (["attraction", "chemistry", "spark", "connection", "magnetism"], "romance"),
    (["date", "courtship", "wooing", "seduction", "flirting"], "romance"),
    (["passionate", "intense", "ardent", "fervent", "fiery"], "romance"),
    (["devotion", "commitment", "loyalty", "faithfulness", "dedication"], "romance"),
    (["soulmate", "partner", "beloved", "darling", "sweetheart"], "romance"),
    (["broken heart", "heartache", "heartbreak", "heartfelt", "heartfelt"], "romance"),
    (["romantic", "literary", "dreamy", "idealistic", "sentimental"], "romance"),
    (["relationship", "love affair", "amour", "passionate love", "true love"], "romance"),
    (["endearment", "pet name", "terms of affection", "love language", "loving"], "romance"),
    (["wedding", "marriage", "bride", "groom", "honeymoon"], "romance"),
    (["seductive", "sexy", "sensual", "erotic", "lustful"], "romance"),
    (["secret admirer", "unrequited love", "crush", "infatuation", "love letter"], "romance"),
    (["first love", "puppy love", "young love", "teen romance", "summer fling"], "romance"),
    (["intimacy", "physical affection", "sexual desire", "romantic attraction", "passion"], "romance"),
    (["long distance", "longing", "missing", "absence", "reunion"], "romance"),
    (["true love", "eternal love", "everlasting love", "unconditional love", "soulful"], "romance"),
    (["ghost", "haunted", "apparition", "poltergeist", "ectoplasm"], "supernatural horror"),
    (["demon", "possession", "exorcism", "hell", "devil"], "supernatural horror"),
    (["witch", "curse", "hex", "magic", "occult"], "supernatural horror"),
    (["vampire", "werewolf", "blood", "curse", "nightmare"], "supernatural horror"),
    (["zombie", "undead", "corpse", "graveyard", "necromancer"], "supernatural horror"),
    (["haunted house", "creepy", "abandoned", "paranormal", "spooky"], "supernatural horror"),
    (["poltergeist", "possession", "evil spirit", "apparition", "ectoplasm"], "supernatural horror"),
    (["psychic", "clairvoyant", "medium", "seance", "ouija board"], "supernatural horror"),
    (["occult", "satanic", "ritual", "sacrifice", "demonic"], "supernatural horror"),
    (["curse", "hex", "witchcraft", "black magic", "conjuring"], "supernatural horror"),
    (["phantom", "apparition", "haunting", "supernatural", "ghostly"], "supernatural horror"),
    (["possession", "demonic", "exorcism", "hellfire", "satanic"], "supernatural horror"),
    (["werewolf", "lycanthrope", "full moon", "transformation", "curse"], "supernatural horror"),
    (["vampire", "dracula", "bloodsucker", "coffin", "stake"], "supernatural horror"),
    (["ghost ship", "haunted", "phantom", "sailing", "paranormal"], "supernatural horror"),
    (["creepy doll", "haunted", "possession", "annabelle", "supernatural"], "supernatural horror"),
    (["zombie apocalypse", "undead", "survival", "infection", "horde"], "supernatural horror"),
    (["demonic possession", "exorcist", "haunted", "paranormal", "demonology"], "supernatural horror"),
    (["haunted forest", "creepy", "spooky", "paranormal", "ghostly"], "supernatural horror"),
    (["witch coven", "sabbath", "curses", "spells", "rituals"], "supernatural horror"),
    (["serendipity", "ethereal", "luminescence", "halcyon", "sonder"], "literary"),
    (["nostalgia", "sonorous", "epiphany", "lucid", "euphoria"], "literary"),
    (["elegance", "bucolic", "ethos", "idyllic", "quintessential"], "literary"),
    (["melancholy", "enigma", "eclectic", "mellifluous", "nebula"], "literary"),
    (["resplendent", "harbinger", "ethereal", "vivacious", "aesthetic"], "literary"),
    (["surreal", "hiraeth", "whimsical", "solitude", "vellichor"], "literary"),
    (["ennui", "gossamer", "ethereal", "ineffable", "ephemeral"], "literary"),
    (["euphony", "evocative", "luminous", "labyrinthine", "petrichor"], "literary"),
    (["mellifluous", "ephemeral", "nebulous", "enchanting", "serene"], "literary"),
    (["serendipity", "melancholy", "halcyon", "ethereal", "euphoria"], "literary"),
    (["surreal", "aesthetic", "ethos", "solitude", "quintessential"], "literary"),
    (["evocative", "bucolic", "luminescence", "lucid", "vellichor"], "literary"),
    (["whimsical", "ineffable", "mellifluous", "eclectic", "resplendent"], "literary"),
    (["luminous", "hiraeth", "petrichor", "serene", "nebula"], "literary"),
    (["vivacious", "enigma", "ephemeral", "idyllic", "mellifluous"], "literary"),
    (["ethereal", "labyrinthine", "harbinger", "euphony", "serendipity"], "literary"),
    (["solitude", "nebulous", "enchanting", "aesthetic", "gossamer"], "literary"),
    (["enigma", "quintessential", "epiphany", "bucolic", "elegance"], "literary"),
    (["surreal", "lucid", "ethos", "luminous", "mellifluous"], "literary"),
    (["mellifluous", "petrichor", "ephemeral", "serene", "ethereal"], "literary")
]





