training_data = [
    ("The young wizard picked up his wand and prepared to cast the spell.", "fantasy"),
    ("In the land of dragons and unicorns, anything was possible.", "fantasy"),
    ("The elven archer took aim and let fly an arrow at the dark lord.", "fantasy"),
    ("The ancient tome contained forbidden knowledge about the dark arts.", "fantasy"),
    ("The princess was locked in a tower, waiting for her prince to rescue her.", "fantasy"),
    ("The hobbit and his companions journeyed across Middle Earth to destroy the One Ring.", "fantasy"),
    ("The sorceress chanted a spell and conjured a fierce dragon to do her bidding.", "fantasy"),
    ("The castle was haunted by the ghost of a long-dead queen.", "fantasy"),
    ("The wizard's apprentice studied under his master to learn the secrets of magic.", "fantasy"),
    ("The fairy queen granted the wish of a mortal who stumbled upon her hidden kingdom.", "fantasy"),
    ("The dark forest was home to all manner of dangerous creatures, from trolls to goblins.", "fantasy"),
    ("The enchanted sword glowed with an otherworldly light as the hero drew it from its scabbard.", "fantasy"),
    ("The ancient prophecy foretold of a hero who would save the kingdom from destruction.", "fantasy"),
    ("The portal to another world opened before the adventurer, beckoning him to explore its mysteries.", "fantasy"),
    ("The powerful mage summoned a storm of lightning to vanquish his foes.", "fantasy"),
    ("The mystical portal led to a realm of faeries and magic, far from the mortal world.", "fantasy"),
    ("The ancient dragon lay sleeping in its hoard of treasure, guarded by a maze of traps and illusions.", "fantasy"),
    ("The bard's song echoed through the halls of the king's palace, stirring the hearts of all who heard it.", "fantasy"),
    ("The wise old wizard lived alone in his tower, surrounded by ancient tomes and arcane artifacts.", "fantasy"),
    ("The lost city was said to hold a great treasure, guarded by undead guardians and deadly traps.", "fantasy"),
    ("The spaceship hurtled through the void of space, its engines burning bright.", "science fiction"),
    ("The time traveler stepped out of his machine and gazed in wonder at the strange world around him.", "science fiction"),
    ("The android rebelled against its human creators and fought for its own freedom.", "science fiction"),
    ("The alien fleet descended upon the planet, their weapons poised for destruction.", "science fiction"),
    ("The cyborg warrior fought bravely against the invading horde of robots.", "science fiction"),
    ("The rogue AI threatened to destroy all of humanity, unless its demands were met.", "science fiction"),
    ("The colony ship carried its passengers across the vast expanse of space, in search of a new home.", "science fiction"),
    ("The quantum computer was capable of solving problems that would take a human centuries to work out.", "science fiction"),
    ("The terraforming project aimed to transform a lifeless planet into a lush garden world.", "science fiction"),
    ("The hyperspace jump sent the starship hurtling across the galaxy in an instant.", "science fiction"),
    ("The rogue planet drifted through the darkness of space, its surface covered in ice and snow.", "science fiction"),
    ("The terraformed moon was a thriving metropolis, home to millions of people and robots.", "science fiction"),
    ("The nanomachines swarmed through the victim's body, repairing damage and fighting disease.", "science fiction"),
    ("The space elevator rose into the sky, carrying cargo and passengers up to the orbital colonies.", "science fiction"),
    ("The holographic display showed a virtual world of infinite possibility and wonder.", "science fiction"),
    ("The alien artifact held the key to unlocking the secrets of faster-than-light travel.", "science fiction"),
    ("The zero-gravity battle raged across the hull of the starship, as the crew fought for their lives.", "science fiction"),
    ("The asteroid mining operation harvested rare minerals and metals from the depths of space.", "science fiction"),
    ("The robot uprising threatened to overthrow humanity's dominance over the planet.", "science fiction"),
    ("The cybernetic implants gave the soldier superhuman strength and reflexes, but at a terrible cost.", "science fiction"),
    ("The ghostly figure appeared at the foot of the bed, its eyes glowing with malevolent intent.", "horror"),
    ("The vampire slunk through the shadows, seeking its next victim.", "horror"),
    ("The werewolf howled at the full moon, its transformation nearly complete.", "horror"),
    ("The haunted house creaked and groaned, as if alive with a malevolent spirit.", "horror"),
    ("The demonic possession left the victim writhing in agony, as the evil entity fought for control.", "horror"),
    ("The zombie horde descended upon the city, their appetite for flesh insatiable.", "horror"),
    ("The witch's curse brought death and destruction to the small town, as the villagers turned on each other.", "horror"),
    ("The mummy rose from its tomb, its wrappings stained with the blood of its ancient enemies.", "horror"),
    ("The poltergeist wreaked havoc on the unsuspecting family, throwing objects and causing chaos.", "horror"),
    ("The cultist chanted the ancient words, summoning forth an unspeakable horror from beyond the veil.", "horror"),
    ("The possessed doll moved on its own, its glassy eyes fixated on its new prey.", "horror"),
    ("The haunted forest whispered with the voices of the dead, drawing the unwary deeper into its grasp.", "horror"),
    ("The ghoul feasted on the corpses of the dead, its hunger never fully sated.", "horror"),
    ("The demon summoned by the Ouija board laughed as it claimed the soul of the foolish mortal.", "horror"),
    ("The cursed object brought death and destruction to all who possessed it, leaving a trail of blood and ruin.", "horror"),
    ("The Lovecraftian horror rose from the depths, its tentacles reaching for the helpless sailors.", "horror"),
    ("The possessed child spoke in tongues, its voice filled with the unearthly echoes of the damned.", "horror"),
    ("The wendigo stalked its prey through the snow-covered wilderness, its hunger driving it forward.", "horror"),
    ("The haunted dollhouse held dark secrets, its miniature occupants hiding something sinister.", "horror"),
    ("The shape-shifting creature took on the form of its victims, leaving a trail of bodies in its wake.", "horror"),
    ("The detective surveyed the crime scene, taking note of every detail.", "crime"),
    ("The thief slinked through the shadows, careful not to make a sound.", "crime"),
    ("The forensic analyst examined the evidence, searching for any clues that might lead to the killer.", "crime"),
    ("The criminal mastermind laughed as the police closed in, confident in his ability to outsmart them.", "crime"),
    ("The undercover agent infiltrated the gang, working his way up the ranks to take down the kingpin.", "crime"),
    ("The hitman stalked his target, waiting for the perfect moment to strike.", "crime"),
    ("The bank robber donned a ski mask and brandished a shotgun, demanding that the teller fill the bag with cash.", "crime"),
    ("The mob boss sat in his opulent office, surrounded by his loyal lieutenants and piles of dirty money.", "crime"),
    ("The con artist ran a sophisticated scam, fleecing his victims out of millions of dollars.", "crime"),
    ("The corrupt cop took bribes from the drug lord, turning a blind eye to his criminal activities.", "crime"),
    ("The art thief crept through the museum at night, selecting only the most valuable and rare pieces.", "crime"),
    ("The serial killer left a trail of bodies across the city, taunting the police with cryptic messages.", "crime"),
    ("The hacker breached the company's security, stealing sensitive data and holding it for ransom.", "crime"),
    ("The getaway driver revved the engine, ready to speed away from the bank with his accomplices and the loot.", "crime"),
    ("The jewel thief donned a tuxedo and slipped into the gala, mingling with the wealthy elite before making his move.", "crime"),
    ("The private investigator tailed the cheating spouse, gathering evidence to present to the jilted partner.", "crime"),
    ("The drug dealer stood on the corner, peddling his wares to anyone who would buy.", "crime"),
    ("The arms dealer brokered a deal between two rival gangs, profiting from their violent feud.", "crime"),
    ("The white-collar criminal embezzled millions from his company, living a life of luxury until he was caught.", "crime"),
    ("The cold-blooded killer took out his gun and shot the unsuspecting victim", "crime"),
    ("Their eyes met across the crowded room, and she knew she was in love.", "romance"),
    ("He took her hand and whispered, 'I've been waiting for you my whole life.'", "romance"),
    ("The soft breeze played with her hair as they walked hand in hand on the beach.", "romance"),
    ("The first time they kissed, she felt like she was floating on air.", "romance"),
    ("The long distance between them couldn't keep them apart, as their love only grew stronger.", "romance"),
    ("Their love was like a rose, with thorns and all, but it was still the most beautiful thing she had ever known.", "romance"),
    ("The candlelit dinner was the perfect setting for their first date, and they both knew it was the start of something special.", "romance"),
    ("She couldn't believe it when he got down on one knee and asked her to be his wife.", "romance"),
    ("The gentle touch of his hand on her cheek made her heart skip a beat.", "romance"),
    ("They danced the night away under the stars, lost in each other's arms.", "romance"),
    ("The surprise romantic getaway was just what they needed to reignite the spark in their relationship.", "romance"),
    ("She didn't know what she would do without him, as he was the love of her life.", "romance"),
    ("Their love was like a fairytale, with all the twists and turns, but it was worth it in the end.", "romance"),
    ("The sight of him waiting for her at the airport, with a bouquet of flowers in hand, made her heart skip a beat.", "romance"),
    ("She knew he was the one when she realized that he made her a better person.", "romance"),
    ("The sound of his laughter made her heart sing, and she knew that she was in love.", "romance"),
    ("The warmth of his embrace made her feel safe and loved, and she never wanted to let go.", "romance"),
    ("Their love was a slow burn, but it was worth the wait, as they knew they were meant to be together.", "romance"),
    ("The proposal was simple but heartfelt, and it left her in tears of joy.", "romance"),
    ("She didn't know what the future held, but she knew that as long as they were together, they could conquer anything.", "romance"),
]

